# Link settings
baseurl: ""
url: "https://ehsanmnd.github.io"
permalink: pretty



# Build settings
markdown: kramdown


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Pagination settings
paginate: 6
paginate_path: "/page/:num"

# Language settings
languages: ["fa", "en"]
default_lang: "fa"


sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  - scope:
      path: ""
    values:
      lang: "fa"
      direction: "rtl"
  - scope:
      path: "en"
    values:
      lang: "en"
      direction: "ltr"
  - scope:
      path: "assets/images"
      type: "posts"
    values:
      layout: "post"
      author: "Ehsan Maminejad"
      comments: true
  - scope:
      path: "life/_posts/fa"
      type: "posts"
    values:
      lang: "fa"
      direction: "rtl"
  - scope:
      path: "life/_posts/en"
      type: "posts"
    values:
      lang: "en"
      direction: "ltr"



# Markdown settings
kramdown:
  input: GFM
  parse_block_html: true
  syntax_highlighter: rouge

# Development settings
watch: true
safe: true

# Exclude from processing
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - LICENSE
  - CNAME
  - .jekyll-cache
  - .sass-cache