#-------------------------------
# Site Settings
logo: logo.svg
title: "بوف بینا"
description: "بوف بینا | هم می‌فهمم، هم می‌سازم"

#-------------------------------
# Author Settings
author:
  name: Ehsan Maminejad
  image: 01.jpg

# Contact links
github: https://github.com/ehsanmnd
linkedin: https://www.linkedin.com/in/ehsanmaminejad

#-------------------------------
# Contact Settings
contact:
  email: ehsan.maminejad@gmail.com

#-------------------------------
# Analytics Settings
google-analytics: G-18WKJXFHXS

#-------------------------------
# Build Settings
disqus-identifier: Echius